@port={{$dotenv SERVER_PORT}}
@base=http://localhost:{{port}}/api/v1

# register
POST {{base}}/register
Content-Type: application/json
 
{
  "email": "blabla@bla.com",
  "password":"secret_pass",
  "first_name":"test",
  "last_name":"totest"
}

###
# login

POST {{base}}/login
Content-Type: application/json

{
  "email": "blabla@bla.com",
  "password":"secret_pass"
}